### PR TITLE
🧑‍💻 improve deploy script

### LINKED ISSUE #37: Improve deploy script to manage owners
In the current situation all deployed contracts are owned by the admin address, therefore we have to manually transfer the ownership of the nft contract from admin to minter contract.

Using [`starknet invoke`](https://docs.starknet.io/docs/CLI/commands#starknet-invoke) we should be able to handle thise automatically after deployments.

### PR DESCRIPTION
**Pull request by Bal7hazar**
Fix #37 

- [x] add erc721 transfer ownership to set minter as owner
- [x] update protostar version
- [x] fix deploy script according to latest protostar modifications

### CODE REVIEW

**Comment by cloudvenger** [comment]
In the file "protostar,toml", you need to change the target value with:
```
["protostar.config"]
protostar_version = "0.3.2"
```

**Comment by Bal7hazar** [comment]
> In the file "protostar,toml", you need to change the target value with:
> 
> ```
> ["protostar.config"]
> protostar_version = "0.3.2"
> ```

Please see my note [here](https://github.com/Carbonable/carbonable-starknet/pull/44#issuecomment-1223642947).

**Comment by cloudvenger** [comment]
@Bal7hazar , I don't know if you saw it, I asked question on codeline during the review. 

In addition, as I approved and merge the PR https://github.com/Carbonable/carbonable-starknet/pull/44

Now we need to pull the last main branch before merge this PR.

**Comment by Bal7hazar** [comment]
@cloudvenger, I merged the latest main.
I'll merge after your approval.

**Review by cloudvenger — APPROVED** [review]

**Pull request merged**
