### PR TITLE
Implement integration tests

### LINKED ISSUE #10: integrations tests
- [x] Create integration tests (benchmark from [starkvest](https://github.com/abdelhamidbakhta/starkvest/blob/main/tests/integrations/starkvest/test_nominal_case.cairo)) for the mechanism and reproduce the same scenarios that unit tests.

### PR DESCRIPTION
**Pull request by Bal7hazar**
Fixes #10

### CODE REVIEW

**Comment by Bal7hazar** [comment]
The test fails trying to provide the `payment_token_address` to the CarbonableMinter `constructor` with the following error:

```
ValueError: Felt is expected to be in range
[0; 3618502788666131213697322783095070105623107215331596699973092056135872020481),
got -362061622628499295434391970684231507122906752673953756105719321362030122111
```

Note: I provide the ETH address `0x073314940630fd6dcda0d772d4c972c4e0a9946bef9dabf4ef84eda8ef542b82` which works well in unit tests during the minter instantiation ([here](https://github.com/Carbonable/carbonable-starknet/blob/main/tests/units/test_minter.cairo#L308)).

**Comment by Bal7hazar** [comment]
` __setup__` works fine now, ` buy`  function fails due to an `UNINITIALIZED_CONTRACT` issue, I probably missed some steps before the call.

Note: the ETH right address was `0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7`, and I fixed the felt-type thing by re-assigning the `const`  variable to a `tempvar` before deploying the contracts. I assume `const`  doesn't provide a `felt`, not sure why.

**Comment by Bal7hazar** [comment]
Tests and deployment are quite stable now.
Integration tests are quite poor, I'll increase the coverage scope in the next modifications.

**Comment by Bal7hazar** [comment]
I have added the "no whitelisted" test case, which fails when the user try to buy during the whitelist sale then works when the public sale is on.

A latest feature would be to implement a namespace for ` admin`  and `anyone` with high-level functions to ease the understanding of a test. This new layer could handle context managers and also assert each instruction, I'd like something like:

```cairo
func test_e2e_whitelisted{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}():
    let (initial_token_balance) = payment_token_instance.balanceOf(anyone)
    let (initial_nft_balance) = project_nft_instance.balanceOf(anyone)
    let (spend_amount) = project_nft_instance.estimate_amount(quantity=5)

    admin_instance.add_to_whitelist(account=aynone, slots=5)
    anyone_instance.approve(quantity=5)
    anyone_instance.buy(quantity=5)
    admin_instance.set_whitelisted_sale_open(FALSE)
    admin_instance.set_public_sale_open(TRUE)
    anyone_instance.approve(quantity=1)
    anyone_instance.buy(quantity=1)

    let (token_balance) = payment_token_instance.balanceOf(anyone)
    assert token_balance = SafeUint256.sub_le(initial_token_balance, spend_amount)

    let (nft_balance) = project_nft_instance.balanceOf(anyone)
    assert nft_balance = SafeUint256.add(initial_nft_balance, Uint256(6, 0))
```

**Comment by Bal7hazar** [comment]
I did the refactoring, tests now looks like this:

```cairo
@view
func test_e2e_whitelisted{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}():
    # STORY
    # ---
    # User: ANYONE
    # - wants to buy 6 NFTs (5 whitelist, 1 public)
    # - whitelisted: TRUE
    # - has enough funds: YES
    let (anyone_address) = anyone.get_address()

    admin.add_to_whitelist(account=anyone_address, slots=5)
    anyone.approve(quantity=5)
    anyone.buy(quantity=5)
    admin.set_whitelisted_sale_open(FALSE)
    admin.set_public_sale_open(TRUE)
    anyone.approve(quantity=1)
    anyone.buy(quantity=1)

    return ()
end
```

And I moved all functions to build tests from `test_nominal_case.cairo` to `library.cairo`.

I was not able to move setup itself without moving contract deployment settings. An improvment would be to export these settings into a config file and import it from a hint to be more readable, but maybe overkill.

I'm statified with the current version.

**Review by cloudvenger — APPROVED** [review]

**Pull request merged**
