### PR TITLE
✨ add metadata to erc721 collection

### LINKED ISSUE #32: add metadata to erc721 collection
Since the future stacking contract will probably need information about NFT metadata, we will need to have these information on chain and linked to the ERC-721 collection.

Proposition:

A struct that handle attributes

```cairo
struct Metadata:
    member image_url : felt*
    member external_url : felt
    member description : felt*
    member name : felt*
    member holder : felt*
    member certifier : felt*
    member country : felt*
    member expiration : felt
    member background_color: felt
    member animation_url: felt*
    member background_color: felt*
    member youtube_url: felt*
end
```

A variable storage to store the metadata

```cairo
@storage_var
func metadata() -> (res : Metadata):
end
```

A view for each attribute

```cairo
@view
func image_url() -> (res : felt*)
end

@view
func external_url() -> (res : felt)
end
```

All attributes set once in the constructor.

### PR DESCRIPTION
**Pull request by Bal7hazar**
Fix #32

### CODE REVIEW

**Comment by Bal7hazar** [comment]
I added the following submodules:
- https://github.com/CairOpen/cairopen-contracts (provides a long string management)
- https://github.com/ncitron/cairo-merkle-distributor (sources of merkle features I used)

Note: none of them have tags/releases, so I had to focus the HEAD of main/master branches (wokaround [here](https://twoguysarguing.wordpress.com/2010/11/14/tie-git-submodules-to-a-particular-commit-or-branch/) but quite dirty imo).

**Comment by Bal7hazar** [comment]
I added the following submodule:
- https://github.com/CairOpen/cairopen-contracts (provides a long string management)

Note: it doesn't have tags/releases, so I had to focus the HEAD of the main branch (wokaround [here](https://twoguysarguing.wordpress.com/2010/11/14/tie-git-submodules-to-a-particular-commit-or-branch/) but quite dirty imo).

**Comment by Bal7hazar** [comment]
# Additional notes

## Project constructor

I had to define an additional constructor in `src/project/library.cairo` to instantiate the contract in unit tests, this constructor is not used by the deployed contract since the constructor is inherited from ERC-721 OZ contracts.

## Few renamings

I renamed all "project nft" into "carbonable project" which is more appropriate imho (NFT is more a format than a definition).

## Comments

I updated many comments to match OZ contracts, such as:

```cairo
# ----
# VIEWS
# ----
```

into

```cairo
#
# Getters
#
```

**Comment by Bal7hazar** [comment]
# Deployement

## Goerli
- [Carbonable project](https://goerli.voyager.online/contract/0x03faf4549d1ade361f4e6ca5f659423bed4003746b84bd2bce117c0e03441b2b#readContract)
- [Carbonable minter](https://goerli.voyager.online/contract/0x05d33773b81b8389ff68cb6c52ffd89b248ddcbede377eee021c5a21154993d2)
- Owner: 0x009d02bAA050B9e8F3eb98fF0FA1eDe8e1b20D65CEae9f05E018b4d8dA3E4b7f

**Comment by Bal7hazar** [comment]
@cloudvenger changes has been done, and I succeed to keep "not owner" unit tests buy pranking the admin address, so coverage is the same.

**Review by cloudvenger — APPROVED** [review]

**Pull request merged**
